/** Libellés UI des ActivityLog.action — une seule source pour dashboard et hubs. */
export const ACTIVITY_LABELS: Record<string, string> = {
  "company.created": "Entreprise créée",
  "company.updated": "Entreprise mise à jour",
  "company.lifecycle_changed": "Cycle de vie modifié",
  "company.brief_updated": "Brief commercial mis à jour",
  "company.geocoded": "Localisation géocodée",
  "company.location_saved": "Localisation enregistrée",
  "interaction.created": "Interaction enregistrée",
  "followup.created": "Relance planifiée",
  "followup.completed": "Relance terminée",
  "followup.rescheduled": "Relance reportée",
  "opportunity.created": "Opportunité créée",
  "opportunity.stage_changed": "Stage d'opportunité modifié",
  "quote.created": "Devis créé",
  "quote.status_changed": "Statut de devis modifié",
  "project.created": "Projet créé",
  "project.status_changed": "Statut de projet modifié",
  "task.created": "Tâche créée",
  "task.status_changed": "Statut de tâche modifié",
  "milestone.created": "Jalon créé",
  "milestone.status_changed": "Statut de jalon modifié",
  "calendar.created": "Événement créé",
  "calendar.updated": "Événement modifié",
  "repository.linked": "Repository GitHub associé",
  "repository.unlinked": "Repository GitHub retiré",
  "document.created": "Document ajouté",
  "document.updated": "Document modifié",
  "payment.created": "Paiement enregistré",
  "payment.marked_paid": "Paiement encaissé",
  "payment.status_changed": "Statut de paiement modifié",
  "maintenance.created": "Contrat de maintenance créé",
  "maintenance.updated": "Contrat de maintenance modifié",
  "maintenance.status_changed": "Statut de maintenance modifié",
  "tour.ensured": "Tournée du jour ouverte",
  "tour.stop_added": "Arrêt ajouté à la tournée",
  "tour.stop_removed": "Arrêt retiré de la tournée",
  "tour.stop_visited": "Visite terrain enregistrée",
};
